# Generated by Django 3.2 on 2021-05-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
